### ISSUE TITLE
Add apa7.csl for references

### ISSUE THREAD

**Issue by mscharkow** [ccr-journal/ccr-quarto#9]
CCR uses APA 7, which is easily available here: https://www.zotero.org/styles/apa?source=1

We just need to add the apa7.csl file and add a line to the yaml config.

```
contributes:
  formats:
    common:
      csl: apa7.csl
```
